// VexFlowSharp — C# port of VexFlow (https://vexflow.com)
// MIT License
//
// VisualGalleryComparisonTests — C# output scenes that pair with the VexFlow 5
// gallery references generated by tools/gen-reference-images.mjs.

using System.Collections.Generic;
using System.IO;
using NUnit.Framework;
using VexFlowSharp;
using VexFlowSharp.Api;
using VexFlowSharp.Common.Elements;
using VexFlowSharp.Common.Formatting;
using VexFlowSharp.Skia;
using VexFlowSharp.Tests.Infrastructure;

namespace VexFlowSharp.Tests.Comparison
{
    [TestFixture]
    [Category("Comparison")]
    public class VisualGalleryComparisonTests
    {
        private static string OutputDir
        {
            get
            {
                string assemblyDir = Path.GetDirectoryName(
                    typeof(VisualGalleryComparisonTests).Assembly.Location)!;
                return Path.GetFullPath(
                    Path.Combine(assemblyDir, "../../../Comparison/Output"));
            }
        }

        private static string ReferenceImagesDir
        {
            get
            {
                string assemblyDir = Path.GetDirectoryName(
                    typeof(VisualGalleryComparisonTests).Assembly.Location)!;
                return Path.GetFullPath(
                    Path.Combine(assemblyDir, "../../../reference-images"));
            }
        }

        [SetUp]
        public void SetUp()
        {
            Font.ClearRegistry();
            Font.Load("Bravura", BravuraGlyphs.Data);
        }

        private static string SaveAndAssert(SkiaRenderContext ctx, string filename)
        {
            Directory.CreateDirectory(OutputDir);
            string outPath = Path.Combine(OutputDir, filename);
            ctx.SavePng(outPath);

            Assert.That(File.Exists(outPath), Is.True, $"Output PNG must exist at {outPath}");
            Assert.That(new FileInfo(outPath).Length, Is.GreaterThan(0), "Output PNG must be non-zero bytes");
            return outPath;
        }

        private static void FillWhiteBackground(SkiaRenderContext ctx, double width, double height)
        {
            ctx.Save();
            ctx.SetFillStyle("#FFFFFF");
            ctx.FillRect(0, 0, width, height);
            ctx.Restore();
        }

        private static void AssertGalleryImagesMatch(string actualFilename, string referenceFilename)
        {
            string actualPath = Path.Combine(OutputDir, actualFilename);
            string referencePath = Path.Combine(ReferenceImagesDir, referenceFilename);
            Assert.That(File.Exists(actualPath), Is.True, $"Actual PNG missing: {actualPath}");
            Assert.That(File.Exists(referencePath), Is.True, $"Reference PNG missing: {referencePath}");

            ImageComparisonAssert.AssertImagesMatch(
                File.ReadAllBytes(actualPath),
                File.ReadAllBytes(referencePath),
                thresholdPercent: ImageComparison.CrossEngineThresholdPercent);
        }

        private static Voice Voice4_4(IEnumerable<Tickable> tickables)
        {
            var voice = new Voice(new VoiceTime { NumBeats = 4, BeatValue = 4 });
            voice.AddTickables(new List<Tickable>(tickables));
            return voice;
        }

        [Test]
        public void GalleryTabNotation_RendersToFile()
        {
            using var ctx = new SkiaRenderContext(700, 190);
            FillWhiteBackground(ctx, 700, 190);
            var stave = new TabStave(10, 25, 660);
            stave.AddTabGlyph().SetContext(ctx);
            stave.Draw();

            var notes = new List<TabNote>
            {
                new TabNote(new TabNoteStruct { Positions = new[] { new TabNotePosition { Str = 6, Fret = 3 } }, Duration = "8" }, true),
                new TabNote(new TabNoteStruct { Positions = new[] { new TabNotePosition { Str = 5, Fret = 5 }, new TabNotePosition { Str = 4, Fret = 5 } }, Duration = "8" }, true),
                new TabNote(new TabNoteStruct { Positions = new[] { new TabNotePosition { Str = 2, Fret = "x" }, new TabNotePosition { Str = 3, Fret = 7 } }, Duration = "4d" }, true),
                new TabNote(new TabNoteStruct { Positions = new[] { new TabNotePosition { Str = 2, Fret = 8 }, new TabNotePosition { Str = 4, Fret = 9 } }, Duration = "8" }, true),
                new TabNote(new TabNoteStruct { Positions = new[] { new TabNotePosition { Str = 1, Fret = 10 }, new TabNotePosition { Str = 3, Fret = 9 } }, Duration = "4" }, true),
            };

            Dot.BuildAndAttach(new List<VexFlowSharp.Note> { notes[2] }, allNotes: true);

            var voice = Voice4_4(notes);
            new Formatter().JoinVoices(new List<Voice> { voice }).FormatToStave(new List<Voice> { voice }, stave);
            voice.Draw(ctx, stave);

            new Beam(new List<StemmableNote> { notes[0], notes[1] }).SetContext(ctx).Draw();
            new TabSlide(new TieNotes { FirstNote = notes[1], LastNote = notes[3], FirstIndexes = new[] { 0 } })
                .SetContext(ctx).Draw();
            new TabTie(new TieNotes { FirstNote = notes[3], LastNote = notes[4], FirstIndexes = new[] { 1 }, LastIndexes = new[] { 1 } })
                .SetContext(ctx).Draw();

            SaveAndAssert(ctx, "gallery_tab_notation-vfsharp.png");
        }

        [Test]
        public void GalleryGraceNotes_RendersToFile()
        {
            using var ctx = new SkiaRenderContext(760, 170);
            FillWhiteBackground(ctx, 760, 170);
            var stave = new Stave(10, 25, 730);
            stave.AddClef("treble").AddTimeSignature("4/4").SetContext(ctx);
            stave.Draw();

            var graceA = new List<GraceNote>
            {
                new GraceNote(new GraceNoteStruct { Keys = new[] { "e/4" }, Duration = "32" }),
                new GraceNote(new GraceNoteStruct { Keys = new[] { "f/4" }, Duration = "32" }),
                new GraceNote(new GraceNoteStruct { Keys = new[] { "g/4" }, Duration = "32" }),
            };
            graceA[1].AddModifier(new Accidental("#"), 0);

            var graceB = new List<GraceNote>
            {
                new GraceNote(new GraceNoteStruct { Keys = new[] { "b/4" }, Duration = "8", Slash = true }),
            };

            var graceC = new List<GraceNote>
            {
                new GraceNote(new GraceNoteStruct { Keys = new[] { "e/4" }, Duration = "8" }),
                new GraceNote(new GraceNoteStruct { Keys = new[] { "f/4" }, Duration = "16" }),
                new GraceNote(new GraceNoteStruct { Keys = new[] { "e/4", "g/4" }, Duration = "8" }),
            };
            graceC[2].AddModifier(new Accidental("n"), 0);

            var first = new StaveNote(new StaveNoteStruct { Keys = new[] { "b/4" }, Duration = "4", AutoStem = true });
            first.AddModifier(new GraceNoteGroup(graceA, true).BeamNotes(), 0);
            var second = new StaveNote(new StaveNoteStruct { Keys = new[] { "c/5" }, Duration = "4", AutoStem = true });
            second.AddModifier(new GraceNoteGroup(graceB, true).BeamNotes(), 0);
            var third = new StaveNote(new StaveNoteStruct { Keys = new[] { "c/5", "d/5" }, Duration = "4", AutoStem = true });
            third.AddModifier(new GraceNoteGroup(graceC, true).BeamNotes(), 0);

            var notes = new List<StaveNote>
            {
                first,
                second,
                third,
                new StaveNote(new StaveNoteStruct { Keys = new[] { "a/4" }, Duration = "4", AutoStem = true }),
            };

            var voice = Voice4_4(notes);
            new Formatter().JoinVoices(new List<Voice> { voice }).FormatToStave(new List<Voice> { voice }, stave);
            voice.Draw(ctx, stave);

            SaveAndAssert(ctx, "gallery_grace_notes-vfsharp.png");
        }

        [Test]
        public void GallerySmallModifiers_RendersToFile()
        {
            using var ctx = new SkiaRenderContext(760, 250);
            FillWhiteBackground(ctx, 760, 250);
            var stave = new Stave(10, 60, 730);
            stave.AddClef("treble").AddTimeSignature("4/4").SetContext(ctx);
            stave.Draw();

            var first = new StaveNote(new StaveNoteStruct { Keys = new[] { "c/4" }, Duration = "q" });
            first.AddModifier(new Tremolo(3));
            first.AddModifier(new FretHandFinger("1").SetPosition(ModifierPosition.Left), 0);

            var chord = new ChordSymbol()
                .SetFontSize(14)
                .AddText("F7")
                .AddGlyphOrText("b9", SymbolModifiers.Superscript)
                .AddGlyphOrText("#11", SymbolModifiers.Subscript);
            var second = new StaveNote(new StaveNoteStruct { Keys = new[] { "e/4" }, Duration = "q" });
            second.AddModifier(new StringNumber("3").SetPosition(ModifierPosition.Above), 0);
            second.AddModifier(chord, 0);

            var third = new StaveNote(new StaveNoteStruct { Keys = new[] { "g/4" }, Duration = "q" });
            third.AddModifier(new Vibrato(), 0);
            var fourth = new StaveNote(new StaveNoteStruct { Keys = new[] { "c/5" }, Duration = "q" });

            var notes = new List<StaveNote> { first, second, third, fourth };
            var voice = Voice4_4(notes);
            new Formatter().JoinVoices(new List<Voice> { voice }).FormatToStave(new List<Voice> { voice }, stave);
            voice.Draw(ctx, stave);

            new TextBracket(new TextBracketParams
            {
                Start = first,
                Stop = fourth,
                Text = "8",
                Superscript = "va",
                Position = TextBracketPosition.Top,
            }).SetContext(ctx).Draw();

            new PedalMarking(new[] { first, third, third, fourth })
                .SetType(PedalMarkingType.Mixed)
                .SetContext(ctx)
                .Draw();

            new VibratoBracket(second, fourth).SetContext(ctx).Draw();

            SaveAndAssert(ctx, "gallery_small_modifiers-vfsharp.png");
        }

        [Test]
        public void GalleryStaveModifiers_RendersToFile()
        {
            using var ctx = new SkiaRenderContext(760, 230);
            FillWhiteBackground(ctx, 760, 230);
            var stave = new Stave(20, 75, 700);
            stave.AddModifier(new StaveTempo(new StaveTempoOptions { Name = "Allegro", Duration = "q", Bpm = 120 }, stave.GetX(), -10));
            stave.AddModifier(new StaveSection("A", 0, -5));
            stave.AddModifier(new Volta(VoltaType.BeginEnd, "1.", stave.GetX(), -20));
            stave.AddModifier(new Repetition(RepetitionType.DCAlCoda, stave.GetX(), 10));
            stave.AddModifier(new StaveText("cantabile", StaveModifierPosition.Below, new StaveTextOptions
            {
                Justification = TextJustification.Center,
            }), StaveModifierPosition.Below);
            stave.AddClef("treble").AddTimeSignature("4/4").SetContext(ctx);
            stave.Draw();

            var notes = new List<StaveNote>
            {
                new StaveNote(new StaveNoteStruct { Keys = new[] { "c/4" }, Duration = "q" }),
                new StaveNote(new StaveNoteStruct { Keys = new[] { "d/4" }, Duration = "q" }),
                new StaveNote(new StaveNoteStruct { Keys = new[] { "e/4" }, Duration = "q" }),
                new StaveNote(new StaveNoteStruct { Keys = new[] { "f/4" }, Duration = "q" }),
            };

            var voice = Voice4_4(notes);
            new Formatter().JoinVoices(new List<Voice> { voice }).FormatToStave(new List<Voice> { voice }, stave);
            voice.Draw(ctx, stave);

            SaveAndAssert(ctx, "gallery_stave_modifiers-vfsharp.png");
        }

        [Test]
        public void GalleryTabNotation_PixelComparison()
        {
            GalleryTabNotation_RendersToFile();
            AssertGalleryImagesMatch("gallery_tab_notation-vfsharp.png", "gallery_tab_notation-vexflow.png");
        }

        [Test]
        public void GalleryGraceNotes_PixelComparison()
        {
            GalleryGraceNotes_RendersToFile();
            AssertGalleryImagesMatch("gallery_grace_notes-vfsharp.png", "gallery_grace_notes-vexflow.png");
        }

        [Test]
        public void GallerySmallModifiers_PixelComparison()
        {
            GallerySmallModifiers_RendersToFile();
            AssertGalleryImagesMatch("gallery_small_modifiers-vfsharp.png", "gallery_small_modifiers-vexflow.png");
        }

        [Test]
        public void GalleryStaveModifiers_PixelComparison()
        {
            GalleryStaveModifiers_RendersToFile();
            AssertGalleryImagesMatch("gallery_stave_modifiers-vfsharp.png", "gallery_stave_modifiers-vexflow.png");
        }
    }
}
